### ISSUE TITLE
CookbookSampleFramework.cpp Fails to compile with GCC 12.1 or below and Mingw64 10.0 or below

### ISSUE THREAD

**Issue by richardebel** [PacktPublishing/Vulkan-Cookbook#15]
Compiles OK with VS 2022
[cookbook error.txt](https://github.com/PacktPublishing/Vulkan-Cookbook/files/9168225/cookbook.error.txt)

**Comment by shruthis-shetty** [comment]
Hi @richardebel ,

Can you elaborate more on this issue?
We cannot understand what exactly the issue is.

**Comment by richardebel** [comment]
see the cookbook error.txt file that I attached to the original issue report.  It's beyond my capablility to understand the error.  CommonFiles/CookbookSampleFramework.cpp fails to compile with any gcc release that I have tried.

**Comment by richardebel** [comment]
Also fails to compile with Visual Studio with c++20 standard for the same reason that GCC fails
[vs build.txt](https://github.com/PacktPublishing/Vulkan-Cookbook/files/9387155/vs.build.txt)

**Comment by richardebel** [comment]
This build failure can be fixed in:
 "19 Increasing the performance through increasing the number of separately rendered frames.h"
see attached file

**Comment by richardebel** [comment]
FrameResources( VkCommandBuffer            & command_buffer,
                    VkDestroyer(VkSemaphore)   && image_acquired_semaphore,
                    VkDestroyer(VkSemaphore)   && ready_to_present_semaphore,
                    VkDestroyer(VkFence)       && drawing_finished_fence,
                    VkDestroyer(VkImageView)   && depth_attachment,
                    VkDestroyer(VkFramebuffer) && framebuffer ) :
      CommandBuffer( command_buffer ),
