### ISSUE TITLE
Build failed in Visual Studio Community 2017

### ISSUE THREAD

**Issue by HugoOsornio** [PacktPublishing/Vulkan-Cookbook#2]
Hello

I am facing the following issue when compiling the samples on VS2017 Community

library\common files\VulkanDestroyer.h(384): error C2910: 'VulkanCookbook::VkDestroyer<VkSurfaceKHR>::Destroy': cannot be explicitly specialized

**Comment by Ekzuzy** [comment]
Thanks for the info. I will download VS2017 and check the problem.

**Comment by Ekzuzy** [comment]
Hi.

Could You provide selected SDK version and Platform Toolset settings used during compilation? I've just installed Visual Studio Community 2017 and compiled all the projects without any errors. I've checked all combinations of both VS2017 (v141) and VS2015 (v140) Platform Toolsets and both 8.1 and 10.0.15063.0 Windows SDKs. And I cannot reproduce Your problem.

**Comment by HugoOsornio** [comment]
Hello,

Sure I will provide the details on Monday.
Thanks for looking into it!

**Comment by HugoOsornio** [comment]
Hello again.

Attached is the image of my toolset.

![vulkanerror](https://cloud.githubusercontent.com/assets/25018996/26787585/2ed50a44-49d0-11e7-9e08-9aae379ee713.PNG)

I used cmake to create the project files. Later I will use the .bat file to see if it made a difference.

Cheers,
Hugo

**Comment by HugoOsornio** [comment]
Hello

It compiles now. I had to configure it to use the 64 bit version.
On cmake the user needs to make sure to use the "Visual Studio 15 2017 Win64" option.

I will close the issue now and thanks a lot for your time.

**Comment by Ekzuzy** [comment]
Thanks for the info. It's good to know everything works fine now :-).
