### ISSUE TITLE
Missing header file ?

### ISSUE THREAD

**Issue by ghost** [PacktPublishing/Vulkan-Cookbook#4]
Trying to compile the source on my computer (Visual Studio 13 Community + Windows 10), I had to add:
`#include <memory>`
to the /Library/Source Files/10 Helper Recipes/06 Loading texture data from a file.cpp file (for unique_ptr).

**Comment by Ekzuzy** [comment]
I wonder why Visual Studio 2015 didn't complain about the lack of this header file. I didn't have any problems with compilation using gcc neither. But You're right that this file users needed. Common.h is a better file too include it, though. Thanks for the info!

**Comment by ghost** [comment]
You're welcome ;) I will try to see if I find other things around (just bought the book yesterday, nice job!)

**Comment by Ekzuzy** [comment]
Thanks once again! Both for Your help and for showing Your support by buying my book!
