### ISSUE TITLE
Possible Incorrect Operation in "05 Descriptor Sets/09 Creating an input attachment.cpp"

### ISSUE THREAD

**Issue by millerf1234** [PacktPublishing/Vulkan-Cookbook#9]
On line 54 in the second 'if' statement (the one regarding aspect), the operation being performed is
        (aspect & (VK_IMAGE_ASPECT_DEPTH_BIT | VK_IMAGE_ASPECT_DEPTH_BIT))
Is this supposed to be
        (aspect & (VK_IMAGE_ASPECT_DEPTH_BIT | VK_IMAGE_ASPECT_STENCIL_BIT))

**Comment by Ekzuzy** [comment]
Thanks for pointing this. Your are correct - here we are checking if image should contain color, depth or stencil data. Code is already fixed.
